# Base image
FROM node:18.6.1-alpine3.18

# Set the working directory
WORKDIR /app

# Copy package.json and yarn.lock
COPY package.json yarn.lock ./

# Install dependencies
RUN yarn install --frozen-lockfile

# Copy the entire project
COPY . .

# Build the app
RUN yarn build

# Expose PORT 3000
EXPOSE 3000

# Start the app
CMD ["yarn", "start"]
